"""WAF/CDN detection — identify and adapt to web application firewalls."""
from __future__ import annotations

import logging
from dataclasses import dataclass

import aiohttp

logger = logging.getLogger("vulnhunter.stealth")

WAF_SIGNATURES: list[tuple[str, str, list[str], list[str]]] = [
    # (name, type, header_indicators, body_indicators)
    ("Cloudflare", "CDN/WAF", ["cf-ray", "cf-cache-status", "__cfduid", "cf-request-id"], ["cloudflare", "attention required"]),
    ("AWS WAF", "WAF", ["x-amzn-requestid", "x-amz-apigw-id"], ["awswaf", "request blocked"]),
    ("Akamai", "CDN/WAF", ["x-akamai-transformed", "akamai-grn"], ["akamai", "access denied"]),
    ("Imperva/Incapsula", "WAF", ["x-iinfo", "x-cdn"], ["incapsula", "imperva", "visitorid"]),
    ("Sucuri", "WAF", ["x-sucuri-id", "x-sucuri-cache"], ["sucuri", "cloudproxy"]),
    ("ModSecurity", "WAF", ["server"], ["mod_security", "modsecurity", "not acceptable"]),
    ("F5 BIG-IP", "WAF", ["x-wa-info", "bigipserver"], ["the requested url was rejected"]),
    ("Barracuda", "WAF", ["barra_counter_session"], ["barracuda"]),
    ("Fortinet/FortiWeb", "WAF", ["fortiwafsid"], ["fortiweb", "fortigate"]),
    ("DDoS-Guard", "CDN", ["server"], ["ddos-guard"]),
    ("Wordfence", "WAF", [], ["wordfence", "generated by wordfence"]),
    ("Fastly", "CDN", ["x-served-by", "x-cache", "x-timer"], ["fastly"]),
]


@dataclass
class WAFResult:
    detected: bool
    waf_name: str = ""
    waf_type: str = ""
    confidence: str = "none"  # none, low, medium, high


class WAFDetector:
    """Detect and identify WAF/CDN before scanning."""

    async def detect(self, url: str) -> WAFResult:
        """Send probe requests to detect WAF presence."""
        if not url.startswith(("http://", "https://")):
            url = f"https://{url}"

        results: list[WAFResult] = []

        # Normal request
        normal_result = await self._probe(url, {})
        if normal_result.detected:
            results.append(normal_result)

        # Malicious probe — trigger WAF with common attack pattern
        attack_result = await self._probe(
            url,
            {"User-Agent": "Mozilla/5.0"},
            params="<script>alert(1)</script>&id=1' OR '1'='1",
        )
        if attack_result.detected:
            results.append(attack_result)

        if results:
            best = max(results, key=lambda r: {"high": 3, "medium": 2, "low": 1, "none": 0}[r.confidence])
            return best

        return WAFResult(detected=False)

    async def _probe(
        self, url: str, extra_headers: dict[str, str], params: str = "",
    ) -> WAFResult:
        test_url = f"{url}?test={params}" if params else url

        try:
            async with aiohttp.ClientSession(
                timeout=aiohttp.ClientTimeout(total=10),
            ) as session:
                headers = {"User-Agent": "Mozilla/5.0 (compatible; VulnHunter/2.0)"}
                headers.update(extra_headers)

                async with session.get(test_url, headers=headers, ssl=False, allow_redirects=True) as resp:
                    body = (await resp.text(errors="replace")).lower()
                    resp_headers = {k.lower(): v.lower() for k, v in resp.headers.items()}
                    server = resp_headers.get("server", "")

                    for waf_name, waf_type, header_indicators, body_indicators in WAF_SIGNATURES:
                        score = 0

                        for h_ind in header_indicators:
                            if h_ind.lower() in resp_headers:
                                score += 2
                            if h_ind.lower() in server:
                                score += 2

                        for b_ind in body_indicators:
                            if b_ind in body:
                                score += 1

                        if resp.status == 403 and params:
                            score += 1

                        if score >= 3:
                            return WAFResult(detected=True, waf_name=waf_name, waf_type=waf_type, confidence="high")
                        if score >= 2:
                            return WAFResult(detected=True, waf_name=waf_name, waf_type=waf_type, confidence="medium")
                        if score >= 1:
                            return WAFResult(detected=True, waf_name=waf_name, waf_type=waf_type, confidence="low")

        except Exception as e:
            logger.debug(f"WAF detection probe failed for {url}: {e}")

        return WAFResult(detected=False)
